### ISSUE TITLE
Need to update Facebook API before running

### ISSUE THREAD

**Issue by mozartatplay** [jonathan-cook235/DSSGxUK-ITU#1]
I noticed when running the code that the Facebook API was out of date - and got the following error

Initializing the Facebook Marketing API...
Traceback (most recent call last):
  File "/Users/djohnson/compile/DSSGxUK-ITU/src/scripts/map_offline/data_gathering/opendata_facebook.py", line 18, in fb_api_init
    test = my_account.get_ads()
  File "/Users/djohnson/opt/anaconda3/envs/itu_test_02/lib/python3.9/site-packages/facebook_business/adobjects/adaccount.py", line 1058, in get_ads
    return request.execute()
  File "/Users/djohnson/opt/anaconda3/envs/itu_test_02/lib/python3.9/site-packages/facebook_business/api.py", line 677, in execute
    cursor.load_next_page()
  File "/Users/djohnson/opt/anaconda3/envs/itu_test_02/lib/python3.9/site-packages/facebook_business/api.py", line 841, in load_next_page
    response_obj = self._api.call(
  File "/Users/djohnson/opt/anaconda3/envs/itu_test_02/lib/python3.9/site-packages/facebook_business/api.py", line 350, in call
    raise fb_response.error()
facebook_business.exceptions.FacebookRequestError: 

  Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v11.0/act_87134545/ads
  Params:  {'summary': 'true'}

  Status:  400
  Response:
    {
      "error": {
        "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v12.0.",
        "type": "OAuthException",
        "code": 2635,
        "fbtrace_id": "A_0jGVkOkZdNB-g5FzoksVj"
      }
    }

This can be fixed by updating the Facebook API with
conda install -c conda-forge facebook_business

**Comment by jonathan-cook235** [comment]
Thanks for this! I will close the issue.
